### ISSUE TITLE
[R-T4.2-4] Preconditions for data processing

### ISSUE THREAD

**Issue by v-yussupov** [radon-h2020/radon-particles#10]
| **ID**                        |  **R-T4.2-4**                              |
|-----------------------|----------------------------------|
| Section                       |  WP4: Modeling Environment     |
| Type                           |  FUNCTIONAL_SUITABILITY        |
| User Story                  |  As a Software Designer/Software Developer/QoS Engineer, I want to define preconditions for data pipelines in the application model.        |
| Requirement               | The models should be able to define certain preconditions for filtering which data objects to move/stream through the pipeline.        |
| Extended Description  | For example to filter which types of log entries should be ingested or to only move files that are older than X hours.         |
| Affected Tools             | GRAPHMODEL_TOOL         |
| Means of Verification  | Model review with partners and case study.          |
| Dependency               | T5.4          |

**Comment by v-yussupov** [comment]
@pjakovits could you please check if there were any PRs from UTR that address/resolve this issue?

**Comment by pjakovits** [comment]
@v-yussupov the #105 Pull request addresses this requirement.

**Comment by v-yussupov** [comment]
addressed in the #105
