### ISSUE TITLE
ScaleOut.tosca Policy erroneous trancation of tosca lines

### ISSUE THREAD

**Issue by sydkbc** [radon-h2020/radon-particles#109]
Hello.

I am facing the following issue:
When I include the scaleout.tosca policy through GMT
( radon-particles/policytypes/radon.policies.scaling/ScaleOut/PolicyType.tosca) 
when I export the relevant CSAR file lines 40-53 are truncated.

I think I reported this issue before so I am sending a reminder since the error persists.

Thanks in advance,
Anestis

**Comment by v-yussupov** [comment]
Hello @sydkbc
this truncation happens because YAML Policy Type Trigger Definitions are not yet supported in Winery.
https://github.com/eclipse/winery/pull/628 will add support for these definitions, hence, enabling the correct export.

**Comment by v-yussupov** [comment]
Solved by https://github.com/eclipse/winery/pull/628
