### ISSUE TITLE
[R-T4.2-7] Test case specification

### ISSUE THREAD

**Issue by v-yussupov** [radon-h2020/radon-particles#13]
| **ID**                        |  **R-T4.2-7**                              |
|-----------------------|----------------------------------|
| Section                       |  WP4: Modeling Environment     |
| Type                           |  FUNCTIONAL_SUITABILITY        |
| User Story                  | As a QoS Engineer/Software Developer, I want to define test case specifications in the models.        |
| Requirement               | The models must be able to include the description of test cases for certain components (annotate test-related information).      |
| Extended Description  | There must be test case specifications for components in the model, which are used to generate tests in the final runtime.       |
| Affected Tools             | GRAPHMODEL_TOOL         |
| Means of Verification  | Model review with partners and case study.          |
| Dependency               | N/A          |

**Comment by v-yussupov** [comment]
@duelle could you please reference the PRs which resolved this issue? we can then close it afterwards

**Comment by duelle** [comment]
Resolved by:
- https://github.com/radon-h2020/radon-particles/pull/22
- https://github.com/radon-h2020/radon-particles/pull/34
- https://github.com/radon-h2020/radon-particles/pull/38
