### ISSUE TITLE
[R-T4.2-8] Model API Gateway resources in AWS

### ISSUE THREAD

**Issue by naesheim** [radon-h2020/radon-particles#17]
| **ID** | **R-T4.2-8** |
|---|---|
| Section | WP4: Modeling Environment |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to model API Gateway resources in AWS that trigger functions in AWS Lambda. |
| Requirement | Being able to model API Gateway resources in AWS. |
| Extended Description | A RADON Model should contain an API Gateway resource with respective configuration to trigger a FaaS function hosted in AWS Lambda. |
| Affected Tools | GRAPHMODEL_TOOL |
| Means of Verification | Model review with partners and PRQ case study. |
| Dependency | N/A |

**Comment by miwurster** [comment]
@gcasale please approve.

**Comment by gcasale** [comment]
Sorry but this requires another pass. Please review the process to change requirements. We want to close the old one, open a new one, and link the two.

**Comment by miwurster** [comment]
This is a new requirement. New ones do not have to be approved then?

**Comment by gcasale** [comment]
Ah OK, I saw two changes and I thought it was an old one. Looks good. Approved.
