### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by zhululai** [radon-h2020/radon-particles#3]
No consistent naming convention is applied across all the entities including nodes, relationships, policies, etc. Take the serverless functions for example,

"radon.nodes.aws.LambdaFunction" : [_platform_].[_entity_]
"radon.nodes.azure.AzureFunction" : [_platform_].[_platform_][_entity_]
"radon.nodes.google.CloudFunction" : [_vendor_].[_entity_]

Note that this issue has increasing inertia over time. That is, it is more difficult to resolve later than earlier.

**Comment by miwurster** [comment]
Fixed by #4
