### ISSUE TITLE
Preparation steps before pull requests

### ISSUE THREAD

**Issue by pjakovits** [radon-h2020/radon-particles#35]
As I understand from the discussion in the #27 pull request, it is good to use the "admin repository touch" feature of GMT to test if there are any issues in the models before creating pull request. 

However, I noticed that there are often significant changes to many files, which were not directly modified in the context of the specific pull request. Which may make it a bit difficult to track what files were actually contributed to. 

So I thought Id confirm before creating the next pull request: 
Is is suggested to run  "admin repository touch" feature in GMT every time before a pull request? And include the automatic changes into the pull request?

**Comment by Vogel612** [comment]
The root cause of the unrelated changes lies within the serialization used by winery. Because YAML data is basically stored as a nested Map structure and Java does not guarantee a traversal order for these maps the serialization is partially nondeterministic.

The policy should be to add even unrelated changes after the serialization process has been modified to be deterministic.

**Comment by miwurster** [comment]
Hi, ideally you would execute the "admin repository touch" feature when finalizing your PR but you would only add/commit your files/changes to the latest commit (revert changes on files that are not part of your work).

We currently have an open user story in Winery to adapt the serialization process to be more deterministic (as mentioned by @Vogel612).

**Comment by pjakovits** [comment]
> Hi, ideally you would execute the "admin repository touch" feature when finalizing your PR but you would only add/commit your files/changes to the latest commit (revert changes on files that are not part of your work).

Ok, I will do so. From my side, the question can be closed.
