### ISSUE TITLE
Implementation for Azure nodes

### ISSUE THREAD

**Issue by giopnd** [radon-h2020/radon-particles#81]
The Azure related nodes seems to have no implementation. 

is it possible to provide an implementation for:

- An Azure FaaS triggered by a blob storage
- an azure blob storage

?

**Comment by miwurster** [comment]
Hey, what about these examples:
- https://github.com/radon-h2020/demo-tosca-blueprint-azure-function
- https://github.com/radon-h2020/demo-tosca-blueprint-faas-aws-azure

**Comment by giopnd** [comment]
hmm i didn't noticed those examples. i will try to validate them. thanks.

**Comment by giopnd** [comment]
i think the node types implemented at https://github.com/radon-h2020/demo-tosca-blueprint-azure-function.git are what i need. 
@cankarm   @anzoman  Can you please create a merge request so that i can access the Azure nodes from within the particles?

thanks in advance.

**Comment by anzoman** [comment]
@giopnd aha I see that there's no modules for Azure Container and Container notification (FaaS trigger) in particles. @cankarm, @miwurster  would it be okay if we supply these two modules (from Azure blueprint repo) to particles?

**Comment by cankarm** [comment]
I think that this would be perfect, @anzoman. It seems that we have some pieces already in TPS, so some initial pieces are already done.

**Comment by giopnd** [comment]
hi all,

is there any status update on this?
can i model Azure FaaS and blob storage using the radon-particles?

**Comment by anzoman** [comment]
@giopnd yes this is under development and I will supply a new PR by the end of this week.

**Comment by anzoman** [comment]
@giopnd I've created a PR that will implement Azure modules: #96.

**Comment by miwurster** [comment]
PR is merged. Thanks for the contrib @anzoman!
