### ISSUE TITLE
[R-T4.2-3] Data processing modeling

### ISSUE THREAD

**Issue by v-yussupov** [radon-h2020/radon-particles#9]
| **ID**                        |  **R-T4.2-3**                              |
|-----------------------|----------------------------------|
| Section                       |  WP4: Modeling Environment     |
| Type                           |  FUNCTIONAL_SUITABILITY        |
| User Story                  |  As a Software Designer/Software Developer/Operations Engineer, I want to represent behavioral aspects (e.g. data pipelines, event flow) in my application models.        |
| Requirement               | The models must be able to define different kinds of data processing tasks and control flow elements in order to express the behavior of my application.        |
| Extended Description  | For example, jobs that process analytics data or moving files between different storage systems. Futher, the modeling of timed schedules must be supported.         |
| Affected Tools             | GRAPHMODEL_TOOL         |
| Means of Verification  | Model review with partners and case study.          |
| Dependency               | T5.4          |

**Comment by v-yussupov** [comment]
@pjakovits could you please reference the PRs (at least the major ones) that resolve this issue?

**Comment by pjakovits** [comment]
This was resolved by #77 which added data pipeline-related node types for data analytics.
@v-yussupov

**Comment by v-yussupov** [comment]
Resolved by #77
